### ISSUE TITLE
주어진 미션에 대한 modify버튼 작동 수정

### ISSUE THREAD

**Issue by ghost** [CAU-OSS-2019/team-project-team4#10]
프로그램을 실행시켜보았더니 주어진 미션에 대한 modify버튼이 정상적으로 작동하지 않는 것 같았습니다. 포크를 따서  modify관련 코드의 front, backend부분을 수정한 후 풀리퀘 요청을 보내겠습니다.

**Comment by canis617** [comment]
풀리퀘스트 확인 됬습니다. 많은 conflict로 인해 새로운 브랜치를 생성하여 그곳에 pull request를 요청해주세요.

**Comment by canis617** [comment]
해당 기능을 위한 branch를 modify로 생성해 놓겠습니다.

**Comment by canis617** [comment]
주어진 파일을 직접수정하셔서 덮어 쓰셨나봅니다.
또한 code형식이 달라 conflict가 일어나였습니다.
하지만 기본 기능구현과 서버 연동부분이 잘 구현되어있어
문법을 제외한 부분은 건드릴 곳이 없었고 master에 merge 시켰습니다.

**Comment by canis617** [comment]
해당 기능은 구현이 완료되었으므로 issue를 종료하겠습니다.

**Comment by canis617** [comment]
추가적으로 modify branch는 더이상 필요없으므로 삭제하였습니다.
